name: Deploy to AAAA

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '>=16.14'

      - name: Install dependencies
        run: |
          npm install
          pwd
      - name: Build website
        run: |
          pwd 
          npm run build

      - name: Deploy to AAAA
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: ./build
          token: ${{ secrets.YISHUI_TOKEN }}
